using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.UI;

[RequireComponent (typeof (Image))]
public class UGUISpriteAnimation : MonoBehaviour {
    private Image ImageSource;
    private int mCurFrame = 0;
    private float mDelta = 0;

    public float FPS = 5;
    public List<Sprite> SpriteFrames = new List<Sprite> ();
    public bool IsPlaying = false;
    public bool Foward = true;
    public bool AutoPlay = false;
    public bool Loop = false;

    public string spriteFilePath = "";
    public int FrameCount {
        get {
            return SpriteFrames.Count;
        }
    }

    public System.Action animFinsih;

    void Awake () {
        ImageSource = GetComponent<Image> ();
    }

    void Start () {
        if (AutoPlay) {
            Play ();
        } else {
            IsPlaying = false;
        }
    }

    private void SetSprite (int idx) {
        ImageSource.sprite = SpriteFrames[idx];
        ImageSource.SetNativeSize ();
    }

    public void Play () {
        IsPlaying = true;
        Foward = true;
    }

    public void PlayReverse () {
        IsPlaying = true;
        Foward = false;
    }

    void Update () {
        if (!IsPlaying || 0 == FrameCount) {
            return;
        }
        mDelta += Time.deltaTime;
        if (mDelta > 1 / FPS) {
            mDelta = 0;
            if (Foward) {
                mCurFrame++;
            } else {
                mCurFrame--;
            }

            if (mCurFrame >= FrameCount) {
                if (Loop) {
                    mCurFrame = 0;
                } else {
                    IsPlaying = false;
                    if (animFinsih != null) {
                        animFinsih ();
                    }
                    return;
                }
            } else if (mCurFrame < 0) {
                if (Loop) {
                    mCurFrame = FrameCount - 1;
                } else {
                    IsPlaying = false;
                    if (animFinsih != null) {
                        animFinsih ();
                    }
                    return;
                }
            }
            SetSprite (mCurFrame);
        }
    }

    public void Pause () {
        IsPlaying = false;
    }

    public void Resume () {
        if (!IsPlaying) {
            IsPlaying = true;
        }
    }

    public void Stop () {
        mCurFrame = 0;
        SetSprite (mCurFrame);
        IsPlaying = false;
    }

    public void Rewind () {
        mCurFrame = 0;
        SetSprite (mCurFrame);
        Play ();
    }

    [ContextMenu ("getImage")]
    public void getCarImage () {
        SpriteFrames.Clear ();
        string path = Application.dataPath + "/Resources/" + spriteFilePath;
        if (Directory.Exists (path)) {
            //获取文件信息
            DirectoryInfo direction = new DirectoryInfo (path);

            FileInfo[] files = direction.GetFiles ("*", SearchOption.AllDirectories);

            print (files.Length);

            for (int i = 0; i < files.Length; i++) {
                //过滤掉临时文件
                if (files[i].Name.EndsWith (".meta")) {
                    continue;
                }
                print (files[i].Extension); //这个是扩展名
                //获取不带扩展名的文件名
                string name = Path.GetFileNameWithoutExtension (files[i].ToString ());
                print (name);
                // FileInfo.Name是返回带扩展名的名字 
                SpriteFrames.Add ((Sprite) Resources.Load (spriteFilePath + "/" + name, typeof (Sprite)));
            }
        }
    }
}